### In Graph Neural Networks (GNNs) and point cloud processing (e.g., PointNet++, DGCNN, PyTorch Geometric), a radius graph is a graph where two points are connected if their Euclidean distance is less than or equal to a specified radius r.

Given points,$P={p_1,p_2,p_3,p_n}$

an edge exists between point $p_i$ and $p_j$ if

$$\|p_i-p_j\|\le r$$

where

- r = radius threshold
- ∥⋅∥ = Euclidean distance


| Point | Coordinate |
| ----- | ---------- |
| A     | (0,0)      |
| B     | (1,0)      |
| C     | (2,0)      |
| D     | (0,2)      |
| E     | (5,5)      |

Choose r=1.5



In [3]:
import torch

In [4]:
x=torch.tensor([[
    [0,0],
    [1,0],
    [2,0],
    [0,2],
    [5,5]
]])

In [5]:
x=x.transpose(2,1)

In [6]:
inner=-2*torch.matmul(x.transpose(2,1),x)

In [7]:
xx=torch.sum(x**2,dim=1,keepdim=True)

In [8]:
distance=-xx-inner-xx.transpose(2,1)

In [9]:
distance

tensor([[[  0,  -1,  -4,  -4, -50],
         [ -1,   0,  -1,  -5, -41],
         [ -4,  -1,   0,  -8, -34],
         [ -4,  -5,  -8,   0, -34],
         [-50, -41, -34, -34,   0]]])

In [10]:
from torch_geometric.nn import radius_graph
from torch_geometric.loader import DataLoader

In [11]:
batch = torch.zeros(5, dtype=torch.long)

edge_index = radius_graph(
    x.transpose(1,2),
    r=1.1,
    batch=batch,
    loop=False
)

print(edge_index)

tensor([[3, 3, 0, 1],
        [0, 1, 3, 3]])


In [12]:
edge_index

tensor([[3, 3, 0, 1],
        [0, 1, 3, 3]])

In [13]:
import torch
from torch_geometric.nn import radius_graph


x = torch.tensor([
    [0.0, 0.0],
    [1.0, 0.0],
    [2.0, 0.0],
    [0.0, 2.0],
    [5.0, 5.0]
], dtype=torch.float)


batch = torch.zeros(x.size(0), dtype=torch.long)


edge_index = radius_graph(
    x,
    r=1.5,
    batch=batch,
    loop=False
)

print("Edge Index:")
print(edge_index)

Edge Index:
tensor([[1, 0, 2, 1],
        [0, 1, 1, 2]])


### Comparison
| KNN Graph                                | Radius Graph                      |
| ---------------------------------------- | --------------------------------- |
| Fixed number of neighbors                | Variable number of neighbors      |
| Dense regions lose information           | Dense regions keep more neighbors |
| Sparse regions force long-distance edges | Sparse regions may have no edges  |
| Parameter = k                            | Parameter = radius r              |


In [14]:
torch.__version__

'2.8.0+cu126'