In [111]:
import laspy
import open3d as o3d
import numpy as np

In [112]:
las=laspy.read("sample_data/sample_0000.las")

In [113]:
list(las.point_format.dimension_names)

['X',
 'Y',
 'Z',
 'intensity',
 'return_number',
 'number_of_returns',
 'scan_direction_flag',
 'edge_of_flight_line',
 'classification',
 'synthetic',
 'key_point',
 'withheld',
 'scan_angle_rank',
 'user_data',
 'point_source_id']

In [114]:
points=np.column_stack((las.x,las.y,las.z))

In [115]:
pcd=o3d.geometry.PointCloud()

In [116]:
pcd.points=o3d.utility.Vector3dVector(points-np.mean(points))

In [117]:
o3d.visualization.draw_geometries([pcd])

In [118]:
points

array([[-5.31602244e+00, -1.40158173e+00,  2.69150759e-02],
       [-5.30102244e+00, -1.45658173e+00,  1.99150759e-02],
       [-5.29802244e+00, -1.44958173e+00,  1.91507586e-03],
       ...,
       [ 4.60297756e+00,  5.34418274e-01,  2.19150759e-02],
       [ 4.60497756e+00,  5.10418274e-01,  1.89150759e-02],
       [ 4.60597756e+00,  4.90418274e-01, -8.49241370e-05]],
      shape=(251164, 3))

In [119]:
points[100:200,0]

array([-5.10402244, -5.10402244, -5.10302244, -5.10102244, -5.09902244,
       -5.09902244, -5.09602244, -5.09502244, -5.09202244, -5.09102244,
       -5.08902244, -5.08802244, -5.08602244, -5.08602244, -5.08502244,
       -5.08202244, -5.08002244, -5.08002244, -5.08002244, -5.08002244,
       -5.07902244, -5.07902244, -5.07802244, -5.07702244, -5.07602244,
       -5.07602244, -5.07402244, -5.07302244, -5.07002244, -5.06902244,
       -5.06902244, -5.06802244, -5.06802244, -5.06602244, -5.06502244,
       -5.06302244, -5.06202244, -5.06202244, -5.06102244, -5.05802244,
       -5.05802244, -5.05702244, -5.05402244, -5.05402244, -5.05402244,
       -5.05302244, -5.05302244, -5.05102244, -5.05102244, -5.05002244,
       -5.04902244, -5.04802244, -5.04802244, -5.04802244, -5.04802244,
       -5.04702244, -5.04602244, -5.04602244, -5.04502244, -5.04502244,
       -5.04402244, -5.04302244, -5.04002244, -5.03902244, -5.03702244,
       -5.03702244, -5.03602244, -5.03602244, -5.03602244, -5.03

In [120]:
points.ndim

2

In [121]:
points.dtype

dtype('float64')

#### XYZ Extraction

In [122]:
X=points[:,0]
print(X)

[-5.31602244 -5.30102244 -5.29802244 ...  4.60297756  4.60497756
  4.60597756]


In [123]:
Y=points[:,1]
print(Y)

[-1.40158173 -1.45658173 -1.44958173 ...  0.53441827  0.51041827
  0.49041827]


In [124]:
Z=points[:,2]
print(Z)

[ 2.69150759e-02  1.99150759e-02  1.91507586e-03 ...  2.19150759e-02
  1.89150759e-02 -8.49241370e-05]


#### Statistics

In [125]:
display(np.mean(Z))
display(np.std(Z))
display(np.min(Z))
display(np.max(Z))
display(np.percentile(Z,95))

np.float64(0.21651129586271417)

np.float64(0.26656188994623664)

np.float64(-0.19208492413696732)

np.float64(1.4399150758630328)

np.float64(0.8149150758630328)

#### Boolean Masking

In [126]:
ground=points[:,2]<2
ground_points=points[ground]
display(ground_points)

array([[-5.31602244e+00, -1.40158173e+00,  2.69150759e-02],
       [-5.30102244e+00, -1.45658173e+00,  1.99150759e-02],
       [-5.29802244e+00, -1.44958173e+00,  1.91507586e-03],
       ...,
       [ 4.60297756e+00,  5.34418274e-01,  2.19150759e-02],
       [ 4.60497756e+00,  5.10418274e-01,  1.89150759e-02],
       [ 4.60597756e+00,  4.90418274e-01, -8.49241370e-05]],
      shape=(251164, 3))

#### Vectorized Operation

In [127]:
ground_points*=5
display(ground_points)

array([[-2.65801122e+01, -7.00790863e+00,  1.34575379e-01],
       [-2.65051122e+01, -7.28290863e+00,  9.95753793e-02],
       [-2.64901122e+01, -7.24790863e+00,  9.57537932e-03],
       ...,
       [ 2.30148878e+01,  2.67209137e+00,  1.09575379e-01],
       [ 2.30248878e+01,  2.55209137e+00,  9.45753793e-02],
       [ 2.30298878e+01,  2.45209137e+00, -4.24620685e-04]],
      shape=(251164, 3))

In [128]:
ground_points+=5
display(ground_points)

array([[-21.58011218,  -2.00790863,   5.13457538],
       [-21.50511218,  -2.28290863,   5.09957538],
       [-21.49011218,  -2.24790863,   5.00957538],
       ...,
       [ 28.01488782,   7.67209137,   5.10957538],
       [ 28.02488782,   7.55209137,   5.09457538],
       [ 28.02988782,   7.45209137,   4.99957538]], shape=(251164, 3))

#### Distance

In [129]:
np.linalg.norm(points,axis=1)

array([5.49774957, 5.4975327 , 5.49275273, ..., 4.63394925, 4.63321735,
       4.63201246], shape=(251164,))

#### Unique

In [130]:
np.unique(las.classification)

array([0], dtype=uint8)

#### Stacking

In [131]:
np.column_stack((las.x,las.y,las.z))

array([[-5.31602244e+00, -1.40158173e+00,  2.69150759e-02],
       [-5.30102244e+00, -1.45658173e+00,  1.99150759e-02],
       [-5.29802244e+00, -1.44958173e+00,  1.91507586e-03],
       ...,
       [ 4.60297756e+00,  5.34418274e-01,  2.19150759e-02],
       [ 4.60497756e+00,  5.10418274e-01,  1.89150759e-02],
       [ 4.60597756e+00,  4.90418274e-01, -8.49241370e-05]],
      shape=(251164, 3))

In [132]:
np.vstack((las.x,las.y,las.z))

array([[-5.31602244e+00, -5.30102244e+00, -5.29802244e+00, ...,
         4.60297756e+00,  4.60497756e+00,  4.60597756e+00],
       [-1.40158173e+00, -1.45658173e+00, -1.44958173e+00, ...,
         5.34418274e-01,  5.10418274e-01,  4.90418274e-01],
       [ 2.69150759e-02,  1.99150759e-02,  1.91507586e-03, ...,
         2.19150759e-02,  1.89150759e-02, -8.49241370e-05]],
      shape=(3, 251164))

In [133]:
np.hstack((las.x,las.y,las.z))

array([-5.31602244e+00, -5.30102244e+00, -5.29802244e+00, ...,
        2.19150759e-02,  1.89150759e-02, -8.49241370e-05], shape=(753492,))

#### Broadcasting

In [134]:
points-np.mean(points)

array([[-5.04009848, -1.12565777,  0.30283903],
       [-5.02509848, -1.18065777,  0.29583903],
       [-5.02209848, -1.17365777,  0.27783903],
       ...,
       [ 4.87890152,  0.81034223,  0.29783903],
       [ 4.88090152,  0.78634223,  0.29483903],
       [ 4.88190152,  0.76634223,  0.27583903]], shape=(251164, 3))

#### Random Sampling

In [135]:
np.random.choice(10,2)

array([4, 9])

#### Separate XYZ

In [136]:
X=points[:,0]
print(X)

[-5.31602244 -5.30102244 -5.29802244 ...  4.60297756  4.60497756
  4.60597756]


In [137]:
Y=points[:,1]
print(Y)

[-1.40158173 -1.45658173 -1.44958173 ...  0.53441827  0.51041827
  0.49041827]


In [138]:
Z=points[:,2]
print(Z)

[ 2.69150759e-02  1.99150759e-02  1.91507586e-03 ...  2.19150759e-02
  1.89150759e-02 -8.49241370e-05]


#### Maximum Height

In [139]:
np.max(Z)

np.float64(1.4399150758630328)

#### Ground point

In [140]:
Z[Z<1]

array([ 2.69150759e-02,  1.99150759e-02,  1.91507586e-03, ...,
        2.19150759e-02,  1.89150759e-02, -8.49241370e-05], shape=(251093,))

#### point 10 meter shift

In [141]:
points+=10
print(points)

[[ 4.68397756  8.59841827 10.02691508]
 [ 4.69897756  8.54341827 10.01991508]
 [ 4.70197756  8.55041827 10.00191508]
 ...
 [14.60297756 10.53441827 10.02191508]
 [14.60497756 10.51041827 10.01891508]
 [14.60597756 10.49041827  9.99991508]]


#### Point cloud center

In [142]:
points-np.mean(points)

array([[-5.04009848, -1.12565777,  0.30283903],
       [-5.02509848, -1.18065777,  0.29583903],
       [-5.02209848, -1.17365777,  0.27783903],
       ...,
       [ 4.87890152,  0.81034223,  0.29783903],
       [ 4.88090152,  0.78634223,  0.29483903],
       [ 4.88190152,  0.76634223,  0.27583903]], shape=(251164, 3))

#### 95 percentile height

In [143]:
np.percentile(points,95)

np.float64(12.217418273716675)

#### All classification

In [144]:
np.unique(las.classification)

array([0], dtype=uint8)