In [53]:
import laspy
import open3d as o3d
import numpy as np

In [54]:
las=laspy.read("sample_data/sample_0000.las")

In [55]:
print(type(las))
print(dir(las))
print(help(las))
print(las.header)

<class 'laspy.lasdata.LasData'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_points', '_write_to', 'add_extra_dim', 'add_extra_dims', 'change_scaling', 'evlrs', 'header', 'point_format', 'points', 'remove_extra_dim', 'remove_extra_dims', 'update_header', 'vlrs', 'write', 'xyz']
Help on LasData in module laspy.lasdata object:

class LasData(builtins.object)
 |  LasData(header: laspy.header.LasHeader, points: Union[laspy.point.record.PackedPointRecord, laspy.point.record.ScaleAwarePointRecord, NoneType] = None) -> None
 |
 |  Class synchronizing all the moving parts of LAS files.
 |
 |  It connects the point record, head

In [56]:
print(dir(las.header))

['DEFAULT_POINT_FORMAT', 'DEFAULT_VERSION', '_OLD_LASPY_NAMES', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_point_format', '_prefetch_header_data', '_sync_extra_bytes_vlr', '_version', '_vlrs', 'add_crs', 'add_extra_dim', 'add_extra_dims', 'are_points_compressed', 'copy', 'creation_date', 'evlrs', 'extra_header_bytes', 'extra_vlr_bytes', 'file_source_id', 'generating_software', 'global_encoding', 'gps_time_offset', 'grow', 'major_version', 'max_gps_time', 'max_point_count', 'maxs', 'min_gps_time', 'minor_version', 'mins', 'number_of_evlrs', 'number_of_points_by_return', 'offset_to_point_data', 'offsets', 'parse_crs', 'partial_reset', 'point_count', 'point_for

In [57]:
print(las.header.version)

1.2


In [58]:
print(las.header.point_count)

251164


In [59]:
print(list(las.header.point_format.dimension_names))

['X', 'Y', 'Z', 'intensity', 'return_number', 'number_of_returns', 'scan_direction_flag', 'edge_of_flight_line', 'classification', 'synthetic', 'key_point', 'withheld', 'scan_angle_rank', 'user_data', 'point_source_id']


In [60]:
las.header.scales

array([0.001, 0.001, 0.001])

In [61]:
las.header.offsets

array([-5.31602244, -5.44558173, -0.19208492])

In [62]:
las.header.mins

array([-5.31602244, -5.44558173, -0.19208492])

In [63]:
las.header.maxs

array([4.60597756, 4.54841827, 1.43991508])

#### Point Dimensions

In [64]:
print(las.x)

<ScaledArrayView([-5.31602244 -5.30102244 -5.29802244 ...  4.60297756  4.60497756
  4.60597756])>


In [65]:
print(las.y)

<ScaledArrayView([-1.40158173 -1.45658173 -1.44958173 ...  0.53441827  0.51041827
  0.49041827])>


In [66]:
print(las.z)

<ScaledArrayView([ 2.69150759e-02  1.99150759e-02  1.91507586e-03 ...  2.19150759e-02
  1.89150759e-02 -8.49241370e-05])>


In [67]:
print(las.intensity)

[0 0 0 ... 0 0 0]


In [68]:
print(las.classification)

<SubFieldView([0 0 0 ... 0 0 0])>


In [69]:
print(np.unique(las.classification))

[0]


#### Number of Points

In [70]:
len(las.points)

251164

In [71]:
len(las.x)

251164

In [72]:
points=np.column_stack((las.x,las.y,las.z))


In [73]:
points.shape

(251164, 3)

#### XYZ → NumPy

In [74]:
points=np.column_stack((las.x,las.y,las.z))
points

array([[-5.31602244e+00, -1.40158173e+00,  2.69150759e-02],
       [-5.30102244e+00, -1.45658173e+00,  1.99150759e-02],
       [-5.29802244e+00, -1.44958173e+00,  1.91507586e-03],
       ...,
       [ 4.60297756e+00,  5.34418274e-01,  2.19150759e-02],
       [ 4.60497756e+00,  5.10418274e-01,  1.89150759e-02],
       [ 4.60597756e+00,  4.90418274e-01, -8.49241370e-05]],
      shape=(251164, 3))

#### NumPy → Open3D

In [75]:
pcd=o3d.geometry.PointCloud()

In [76]:
pcd.points=o3d.utility.Vector3dVector(points)

In [77]:
pcd.points

std::vector<Eigen::Vector3d> with 251164 elements.
Use numpy.asarray() to access data.

#### Open3D → NumPy

In [78]:
xyz=np.asarray(points)

In [79]:
xyz

array([[-5.31602244e+00, -1.40158173e+00,  2.69150759e-02],
       [-5.30102244e+00, -1.45658173e+00,  1.99150759e-02],
       [-5.29802244e+00, -1.44958173e+00,  1.91507586e-03],
       ...,
       [ 4.60297756e+00,  5.34418274e-01,  2.19150759e-02],
       [ 4.60497756e+00,  5.10418274e-01,  1.89150759e-02],
       [ 4.60597756e+00,  4.90418274e-01, -8.49241370e-05]],
      shape=(251164, 3))

In [80]:
o3d.visualization.draw_geometries([pcd])

#### Coordinate Frame

In [81]:
frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=4.0,
    origin=[0,0,0]
)

o3d.visualization.draw_geometries([pcd, frame])

#### Multiple las file

In [82]:
las1=laspy.read("sample_data/sample_0001.las")
las2=laspy.read("sample_data/sample_0002.las")
points1=np.column_stack((las1.x,las1.y,las1.z))
points2=np.column_stack((las2.x,las2.y,las2.z))

In [83]:
pcd1=o3d.geometry.PointCloud()
pcd1.points=o3d.utility.Vector3dVector(points1)
pcd2=o3d.geometry.PointCloud()
pcd2.points=o3d.utility.Vector3dVector(points2)



In [84]:
frame=o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=4.0,
    origin=[0,0,0]
)
o3d.visualization.draw_geometries([pcd1,pcd2,frame])

#### Save Point Cloud

In [85]:
o3d.io.write_point_cloud("sample_data/test.ply",pcd)

True

In [86]:
ply=o3d.io.read_point_cloud("sample_data/test.ply")


In [88]:
frame=o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=1.0,
    origin=[0,0,0]
)

In [89]:
o3d.visualization.draw_geometries([ply,frame])